import { initMenu } from './header/menu.js';
import { initNavegacaoAtual } from './header/navegacao-atual.js';
import { initIdioma } from './idioma/idioma.js';
import { initCubo } from './main/cubo.js';
import initCarrossel from './projetos/initCarrossel.js';
import initModalProjetos from './projetos/initModalProjetos.js';
import initTagHover from './sobreMim/initTagHover.js';
import initSkills from './tecnologias/initSkills.js';
import initTabletCard from './tecnologias/initTabletCard.js';
import initTime from './tecnologias/initTime.js';

initMenu();
initNavegacaoAtual();
initIdioma();
initCubo();
initCarrossel();
initModalProjetos();
initTagHover();
initSkills();
initTabletCard();
initTime();
